package com.springcloud.test.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * history
 * @author 
 */
@Data
public class History implements Serializable {
    private Integer no;

    private Integer red1;

    private Integer red2;

    private Integer red3;

    private Integer red4;

    private Integer red5;

    private Integer red6;

    private Integer blue;

    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table history
     *
     * @mbg.generated Tue Apr 27 15:16:55 CST 2021
     */
    private static final long serialVersionUID = 1L;
}