server:
  port: 8080

spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver

    secondary:
      url: jdbc:mysql://localhost:3306/test2
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 手动确认
        acknowledge-mode: manual
        # 拒绝消息是否重回队列
        default-requeue-rejected: true
      direct:
        acknowledge-mode: manual
    #发布消息是否需要回调确认，配合rabbitTemplate.setConfirmCallback(this);implements RabbitTemplate.ConfirmCallback
    publisher-confirms: true
