spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver

    secondary:
      url: jdbc:mysql://localhost:3306/test2
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest