package com.springcloud.jbsdemo.mapper;

import java.util.List;
import java.util.Map;

import com.springcloud.jbsdemo.model.JbsOrderWorker;

public interface JbsOrderWorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insert(JbsOrderWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insertSelective(JbsOrderWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    List<JbsOrderWorker> getList(Map<String, Object> map);
}