package com.springcloud.jbsdemo.mapper;

import java.util.List;
import java.util.Map;

import com.springcloud.jbsdemo.model.ScriptRoom;

public interface ScriptRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insert(ScriptRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insertSelective(ScriptRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    ScriptRoom selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKeySelective(ScriptRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKey(ScriptRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    List<ScriptRoom> getList(Map<String, Object> map);
}