package com.springcloud.jbsdemo.mapper;

import java.util.List;
import java.util.Map;

import com.springcloud.jbsdemo.model.Script;

public interface ScriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insert(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insertSelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    Script selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKeySelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKey(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table script
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    List<Script> getList(Map<String, Object> map);
}