package com.springcloud.jbsdemo.mapper;

import java.util.List;
import java.util.Map;

import com.springcloud.jbsdemo.model.Worker;

public interface WorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insert(Worker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int insertSelective(Worker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    Worker selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKeySelective(Worker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    int updateByPrimaryKey(Worker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    List<Worker> getList(Map<String, Object> map);
}