package com.springcloud.test.mapper;

import java.util.List;
import java.util.Map;

import com.springcloud.test.model.History;

public interface HistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Tue Apr 27 15:16:55 CST 2021
     */
    int insert(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Tue Apr 27 15:16:55 CST 2021
     */
    int insertSelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Tue Apr 27 15:16:55 CST 2021
     */
    List<History> getList(Map<String, Object> map);
}