package com.springcloud.springcloudshardingjdbcnew.mapper.secondary;

import java.util.List;
import java.util.Map;

import com.springcloud.springcloudshardingjdbcnew.model.secondary.SecondaryUser;

public interface SecondaryUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    int insert(SecondaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    int insertSelective(SecondaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    SecondaryUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    int updateByPrimaryKeySelective(SecondaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    int updateByPrimaryKey(SecondaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 22 09:50:42 CST 2021
     */
    List<SecondaryUser> getList(Map<String, Object> map);

    int replaceUser(SecondaryUser secondaryUser);
}