package com.springcloud.jbsdemo.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * jbs_order_worker
 * @author 
 */
@ApiModel(value = "")
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class JbsOrderWorker implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "")
    private Long orderId;

    @ApiModelProperty(value = "")
    private Long workerId;

    @ApiModelProperty(value = "")
    private String role;

    @ApiModelProperty(value = "是否强制指定 0否 1是")
    private Byte isForce;

    @ApiModelProperty(value = "")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbs_order_worker
     *
     * @mbg.generated Mon Aug 09 16:36:52 CST 2021
     */
    private static final long serialVersionUID = 1L;
}