package com.springcloud.jbsdemo.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * order_worker
 * @author 
 */
@ApiModel(value = "")
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderWorker implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "")
    private Long workerId;

    @ApiModelProperty(value = "")
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
}