package com.springcloud.jbsdemo.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * script_worker
 * @author 
 */
@ApiModel(value = "")
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class ScriptWorker implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "")
    private Long scriptId;

    @ApiModelProperty(value = "角色名称-分组名")
    private String roleName;

    @ApiModelProperty(value = "")
    private Long workerId;

    @ApiModelProperty(value = "组内排序分值")
    private Integer score;

    @ApiModelProperty(value = "")
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table script_worker
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
}