package com.springcloud.jbsdemo.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * script_room
 * @author 
 */
@ApiModel(value = "")
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class ScriptRoom implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "")
    private Long scriptId;

    @ApiModelProperty(value = "")
    private Long roomId;

    @ApiModelProperty(value = "排序值")
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table script_room
     *
     * @mbg.generated Tue Aug 03 11:28:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
}