package com.springcloud.jbsdemo.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * worker_time
 * @author 
 */
@ApiModel(value = "")
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class WorkerTime implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "")
    private Long workerId;

    @ApiModelProperty(value = "")
    private String time;

    @ApiModelProperty(value = "")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table worker_time
     *
     * @mbg.generated Tue Aug 10 09:28:39 CST 2021
     */
    private static final long serialVersionUID = 1L;
}