server:
  port: 9000
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri:
          search-paths:
          username:
          password:
      label: master
