server:
  port: 9000
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://gitee.com/gaoyao99409/springcloud-config-git.git
          search-paths: test-config
          username: gaoyao99409
          password: gaoyao910270
      #label: master
