server:
  port: 9000
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/gaoyao99409/springcloud.git
          search-paths: springcloud-config-git
          username: gaoyao99409
          password: gaoyao910270
      #label: master
